### ISSUE TITLE
Design & implement thread hiding

### ISSUE THREAD

**Issue by Anonyymi** [Anonyymi/miniboard#21]
Design and implement a mechanism for hiding threads.

Options:
- Client-side (localstorage, javascript)
- Server-side (cookies, php)

**Comment by Anonyymi** [comment]
Partially blocked by https://github.com/Anonyymi/miniboard/issues/8 because this option must be available via the menu implemented in that issue.

**Comment by aamm2** [comment]
css is commonly used to hide and show stuff. All you have to do is make your php include a div or class, then close out the div or class at the end of the post. then, you can simply use css to show or hide the div.
https://www.w3schools.com/css/css_display_visibility.asp

**Comment by Anonyymi** [comment]
This is a feature that implements user-specific hiding of threads. User can hide a thread from their view if they don't want to see it. The problem here is to keep track of hidden threads on a per user basis + still fill a page with threads even if user has hidden some.

**Comment by aamm2** [comment]
ahhh vichan did that with js I believe. Not sure if it was persistent tho , like if user changed browser. I would highly suggest installing vichan somewhere, then get the js functions that you want working - then you could easily isolate and "borrow" the code.

**Comment by aamm2** [comment]
hay, here are two extremely simple -but interesting  imageboards. Download both... krila is cool it only shows 1 thread when you go to "reply" mode it shows em all, and you click on the banner to return to the main board. BOTH scripts are only a few short lines of php, both use flatfile so it is super easy to study the code. I think you can find how to save the original filename code in one of them!!!!!!!! Both are super easy to study and very small codebase...check out both and study them closely!!!!!

**Comment by Anonyymi** [comment]
We don't want to borrow code. We simply write efficient minimalistic code to achieve our requirements.

**Comment by aamm2** [comment]
That is very respectable. I always like to look and see how others do stuff tho :)

**Comment by aamm2** [comment]
actually, I just realized that the latest tinyib shows the  hashed filename, then actually shows the original filename too, so the code is right in tinyib on how to show original filename.

**Comment by Anonyymi** [comment]
I'm working on this at the moment. Using PHP Session ID cookie to distinguish clients and handle hiding in database with separate table. It's simple but requires refactoring and polish before I commit it.

**Comment by Anonyymi** [comment]
Done.
