### ISSUE TITLE
demo?

### ISSUE THREAD

**Issue by aamm2** [Anonyymi/miniboard#22]
How bout a demo or at least some screenshots to see what your board looks like? :) 
edit- when it comes to php, if docker has to be used, it is not exactly "Minimalistic imageboard software"--
for php to be "Minimalistic", it should easily run on its own or even any shared host. Maybe our definitions of 
what is minimal are different :)

**Comment by Anonyymi** [comment]
I can add a screenshot. Docker is used for an easy and reproducible local development environment. I shall reconsider the use of the word "minimalistic", since you make a good point (it has 3rd party dependencies, though they are "easily" installed with composer).

**Comment by Anonyymi** [comment]
Screenshot added to README.md

**Comment by aamm2** [comment]
cool, thanks!!! Yeah, I was just thinking that its hard for people to search for imageboards, for example and the there are so many that its hard to figure out what ones to focus on.
