### ISSUE TITLE
Save file as its original filename

### ISSUE THREAD

**Issue by Anonyymi** [Anonyymi/miniboard#23]
Optional possibility to save a file with its original filename.

**Comment by aamm2** [comment]
hay, here are two extremely simple -but interesting imageboards. Download both... krila is cool it only shows 1 thread when you go to "reply" mode it shows em all, and you click on the banner to return to the main board. BOTH scripts are only a few short lines of php, both use flatfile so it is super easy to study the code. I think you can find how to save the original filename code in one of them!!!!!!!! Both are super easy to study and very small codebase...check out both and study them closely!!!!!
https://github.com/aamm2/krila
https://github.com/General-Infinity/4chud

**Comment by aamm2** [comment]
actually, I just realized that the latest tinyib shows the hashed filename, then actually shows the original filename too, so the code is right in tinyib on how to show original filename.

**Comment by aamm2** [comment]
![demo](https://user-images.githubusercontent.com/112229963/188324955-eee753a9-31fd-49e8-806f-6bf9b337bcc8.png)

Here, I uploaded a file called 27.jpg.  It shows the hashed filename, the details, then it shows the original filename as you can see. So the code to solve this issue is definitely right in tinyib.

**Comment by Anonyymi** [comment]
Yes, we keep the original filename, but this issue is about a feature that allows the user to download the file with its original filename instead of the unix-timestamped one.

**Comment by aamm2** [comment]
Ahhhh. Sorry, i did not understand what you meant. check this out tho ...it does exactly that :) 
https://am4.org/vi/js/download-original.js

and i can confirm that vichan installs fine on php 8.1.2 by the way :)

**Comment by aamm2** [comment]
https://am4.org/vi/   here is a working demo of the above. you click on the original filename and it allows you to download it as the original.

**Comment by aamm2** [comment]
So is something like that (using js) an acceptable solution or do you want it hard coded via php? The js solution is an instant solution and quite modular- some ppl do not like js tho.

**Comment by Anonyymi** [comment]
> So is something like that (using js) an acceptable solution or do you want it hard coded via php? The js solution is an instant solution and quite modular- some ppl do not like js tho. If you want i can port the js to tinyib and make it work there, too, in order to show that it is a drop in solution that can work on any board.

I'm coding it in PHP because the JS solution is irreliable in older browsers. The PHP solution only requires a simple endpoint that serves the files with original filenames.

**Comment by aamm2** [comment]
Cool, thanks, was just wondering. Also, i haven't touched vichan in like 3 years, and i gotta say, the current version works great so far on php 8.1.2 -  i did not find anything wrong yet. That is quite remarkable.

**Comment by Anonyymi** [comment]
I am not clicking on your links. Get out. Deleted message.

**Comment by Anonyymi** [comment]
Not required right now.
