### ISSUE TITLE
Plesk Docker manager support?

### ISSUE THREAD

**Issue by ghost** [Anonyymi/miniboard#25]
Was wondering if you are familiar with plesk. In order to make it a bit more modern, they have docker manager built in, so people can run something like a node.js blog like  ghost.org there or anything people make a docker image for. I have only used docker manager there on plesk, it is quite limited and requires someone to make the docker image. 
I do not know how to use docker properly from the command line in a vps, so I have to resort to something like the docker manager in plesk. Unfortunately, I do not know how to make a docker image tho, so im not sure how to make an image of miniboard that can work in plesk. 

If you are not familiar with plesk/docker manager in plesk, any chance you could include the commands to install your board? That would be for people who do not know how to use docker at all... you know, people like me :) If I could get a working board up, I could help you with miniboard. I would not likely be able to do anything profound, but I could help you sort out some of the easier stuff.

**Comment by denamuumi** [comment]
I would not recommends using Docker with Plesk because Plesk has very minimal support for Docker. You would most likely have to configure a lot manually from the command line.

This project currently only uses Docker for development purposes and Docker hosting is not planned.
