### ISSUE TITLE
Implement automatic thread deletion

### ISSUE THREAD

**Issue by Anonyymi** [Anonyymi/miniboard#30]
* Delete threads that are bumped above the max thread limit on boards
* If thread limit is 0, automatic deletion is completely disabled
* Implement automatic deletion as a lightweight 'delete' that only marks thread and its posts deleted
  * This means that the thread is still persisted on database and can be accessed by mods
  * This means threads cannot be bumped to oblivion by spammers

**Comment by denamuumi** [comment]
Hello, I can start working on this.

**Comment by Anonyymi** [comment]
> Hello, I can start working on this.

How are you planning to implement this?

**Comment by denamuumi** [comment]
The limit of threads is presumably per board already defined in config.php as max_threads?

This can be implemented with a function that runs and updates the board thread listing on certain events which are
- new thread created
- thread bumped
- thread deleted

**Comment by Anonyymi** [comment]
Yes it's `max_threads`. Event based solution sounds fine to me.

**Comment by Anonyymi** [comment]
@denamuumi Isn't "new thread created" the only event required for this to work? Those other events just shuffle existing threads around.

**Comment by Anonyymi** [comment]
@denamuumi I'm working on massive refactor while also working on post hiding. I'm sorry about that...

**Comment by Anonyymi** [comment]
This is now done. Threads are deleted completely, no need to keep them in database or on disk.
