### ISSUE TITLE
Implement basic administration functionalities for management

### ISSUE THREAD

**Issue by Anonyymi** [Anonyymi/miniboard#38]
- View reports
- View bans
- View accounts
- View logs
- View posts
- Ban posters
- Delete posts

**Comment by Anonyymi** [comment]
Current management UI supports only import and rebuild features. Extend the UI to support the features listed on this task.

**Comment by verigreppi** [comment]
Created pull request for viewing accounts: https://github.com/Anonyymi/miniboard/pull/43
IDK if it is crap. I have never touched PHP before.

**Comment by Anonyymi** [comment]
> Created pull request for viewing accounts: #43 IDK if it is crap. I have never touched PHP before.

The pull request was okay. Programming this kind of software isn't that complex, so it might even be a good project to start learning PHP with.

**Comment by Anonyymi** [comment]
This is now done.
