### ISSUE TITLE
Bug: Mp3 attachment threads are not clickable in catalog view

### ISSUE THREAD

**Issue by denamuumi** [Anonyymi/miniboard#65]
![image](https://github.com/Anonyymi/miniboard/assets/112209167/44f45aa2-a979-4c48-9411-3b9597ebf6b3)

**Comment by Anonyymi** [comment]
Thanks. Mp3's currently lack a placeholder thumbnail if album image is missing from the file.

**Comment by Anonyymi** [comment]
Anonymous contributor fixed the issue. Done.
